// Code generated by "stringer -output=strings_navpvt.go -trimprefix NavPvt -type=NavPvtFixType"; DO NOT EDIT.

package ubx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NavPvtNoFix-0]
	_ = x[NavPvtDeadReckoning-1]
	_ = x[NavPvtFix2D-2]
	_ = x[NavPvtFix3D-3]
	_ = x[NavPvtGNSS-4]
	_ = x[NavPvtTimeOnly-5]
}

const _NavPvtFixType_name = "NoFixDeadReckoningFix2DFix3DGNSSTimeOnly"

var _NavPvtFixType_index = [...]uint8{0, 5, 18, 23, 28, 32, 40}

func (i NavPvtFixType) String() string {
	if i >= NavPvtFixType(len(_NavPvtFixType_index)-1) {
		return "NavPvtFixType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NavPvtFixType_name[_NavPvtFixType_index[i]:_NavPvtFixType_index[i+1]]
}
